### ISSUE TITLE
AttributeError: module 'distutils' has no attribute 'version'

### ISSUE THREAD

**Issue by JosseVanDelm** [pulp-platform/quantlab#2]
Hi!

I'm trying to run the experiments described in `README.md` to check if I've correctly set up the environment.
However, I can not run it since I get this error:
```sh
(quantlab) quantlab/quantlab [main●] » python main.py --problem=CIFAR10 --topology=VGG configure           
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    from manager.flows import platform
  File "/home/josse/phd/quantlab/quantlab/manager/flows/__init__.py", line 107, in <module>
    from .configure import configure
  File "/home/josse/phd/quantlab/quantlab/manager/flows/configure.py", line 23, in <module>
    from manager.logbook  import Logbook
  File "/home/josse/phd/quantlab/quantlab/manager/logbook/__init__.py", line 22, in <module>
    from .logbook import Logbook
  File "/home/josse/phd/quantlab/quantlab/manager/logbook/logbook.py", line 28, in <module>
    from .logsmanager import LogsManager
  File "/home/josse/phd/quantlab/quantlab/manager/logbook/logsmanager.py", line 27, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/josse/miniconda3/envs/quantlab/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
```
It seems to be related to [this PyTorch issue](https://github.com/pytorch/pytorch/issues/69894)

I've installed the conda environment as per the instruction in `README.md`, here is `conda list`:
<details>

```
(quantlab) quantlab/quantlab [main●] » conda list
# packages in environment at /home/josse/miniconda3/envs/quantlab:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   0.15.0             pyhd3eb1b0_0  
aiohttp                   3.8.1            py38h7f8727e_1  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py38h7f8727e_0  
async-timeout             4.0.1              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1           py38h06a4308_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blinker                   1.4              py38h06a4308_0  
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.4.26            h06a4308_0  
cachetools                4.2.2              pyhd3eb1b0_0  
cairo                     1.14.12              h8948797_3  
certifi                   2022.6.15        py38h06a4308_0  
cffi                      1.15.0           py38h7f8727e_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py38h06a4308_0  
cryptography              3.4.8            py38hd23ed53_0  
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.11.0             pyhd3eb1b0_0  
dataclasses               0.8                pyh6d0b6a4_7  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
docutils                  0.17.1           py38h06a4308_1  
entrypoints               0.4              py38h06a4308_0  
et_xmlfile                1.1.0            py38h06a4308_0  
expat                     2.4.4                h295c915_0  
ffmpeg                    4.3                  hf484d3e_0    pytorch
fontconfig                2.13.1               h6c09931_0  
freetype                  2.11.0               h70c0345_0  
fribidi                   1.0.10               h7b6447c_0  
frozenlist                1.2.0            py38h7f8727e_0  
giflib                    5.2.1                h7b6447c_0  
glib                      2.63.1               h5a9c865_0  
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.6.0              pyhd3eb1b0_0  
google-auth-oauthlib      0.4.1                      py_2  
graphite2                 1.3.14               h295c915_1  
graphviz                  2.40.1               h21bd128_2  
grpcio                    1.42.0           py38hce63b2e_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
harfbuzz                  1.8.8                hffaf4a1_0  
icu                       58.2                 he6710b0_3  
idna                      3.3                pyhd3eb1b0_0  
imagesize                 1.3.0              pyhd3eb1b0_0  
importlib-metadata        4.11.3           py38h06a4308_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.22.0           py38hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
jdcal                     1.4.1              pyhd3eb1b0_0  
jedi                      0.17.0                   py38_0  
jinja2                    3.0.3              pyhd3eb1b0_0  
joblib                    1.1.0              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0              pyhd3eb1b0_2  
jupyter                   1.0.0                    py38_7  
jupyter_client            7.2.2            py38h06a4308_0  
jupyter_console           6.4.3              pyhd3eb1b0_0  
jupyter_core              4.10.0           py38h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
kiwisolver                1.4.2            py38h295c915_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.16.0               h780b84a_0    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.1.0                h2733197_1  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.0.3                h7f8727e_2  
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.2.0                h89dd481_0  
libxcb                    1.15                 h7f8727e_0  
libxml2                   2.9.14               h74e7548_0  
lz4-c                     1.9.3                h295c915_1  
mako                      1.1.4              pyhd3eb1b0_0  
markdown                  3.3.4            py38h06a4308_0  
markupsafe                2.1.1            py38h7f8727e_0  
matplotlib                3.3.4            py38h06a4308_0  
matplotlib-base           3.3.4            py38h62a2d02_0  
mistune                   0.8.4           py38h7b6447c_1000  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h51133e4_0  
multidict                 5.2.0            py38h7f8727e_2  
nbclient                  0.5.13           py38h06a4308_0  
nbconvert                 6.4.4            py38h06a4308_0  
nbformat                  5.3.0            py38h06a4308_0  
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.5            py38h06a4308_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.5.1              pyhd3eb1b0_0  
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
notebook                  6.4.11           py38h06a4308_0  
numpy                     1.20.2           py38h2d18471_0  
numpy-base                1.20.2           py38hfae3a4d_0  
oauthlib                  3.2.0              pyhd3eb1b0_0  
onnx                      1.9.0            py38h93f1957_1    conda-forge
openh264                  2.1.1                h4ff587b_0  
openpyxl                  3.0.7              pyhd3eb1b0_0  
openssl                   1.1.1o               h7f8727e_0  
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.4            py38h2531618_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
pango                     1.42.4               h049681c_0  
parso                     0.8.3              pyhd3eb1b0_0  
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.1            py38h22f2fdc_0  
pip                       21.2.4           py38h06a4308_0  
pixman                    0.40.0               h7f8727e_1  
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
prompt_toolkit            3.0.20               hd3eb1b0_0  
protobuf                  3.16.0           py38h709712a_0    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyjwt                     2.1.0            py38h06a4308_0  
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.18.0           py38heee7806_0  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.2                hcf32534_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.15.1             pyhd3eb1b0_0  
python-graphviz           0.16               pyhd3eb1b0_1  
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.9.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
pytz                      2022.1           py38h06a4308_0  
pyzmq                     22.3.0           py38h295c915_2  
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.3.0              pyhd3eb1b0_0  
qtpy                      2.0.1              pyhd3eb1b0_0  
quantlib                  0.2                      pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.7.2              pyhd3eb1b0_1  
scikit-learn              0.24.2           py38ha9443f7_0  
scipy                     1.6.2            py38had2a1c9_1  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                61.2.0           py38h06a4308_0  
sip                       4.19.13          py38h295c915_0  
six                       1.16.0             pyhd3eb1b0_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
soupsieve                 2.3.1              pyhd3eb1b0_0  
sphinx                    4.0.2              pyhd3eb1b0_0  
sphinx_rtd_theme          0.4.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
sqlite                    3.38.5               hc218d9a_0  
tabulate                  0.8.9            py38h06a4308_0  
tensorboard               2.5.0                      py_0  
tensorboard-plugin-wit    1.6.0                      py_0  
terminado                 0.13.1           py38h06a4308_0  
testpath                  0.6.0            py38h06a4308_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.12               h1ccaba5_0  
torchvision               0.10.0               py38_cu102    pytorch
tornado                   6.1              py38h27cfd23_0  
tqdm                      4.62.1             pyhd3eb1b0_1  
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         4.1.1                hd3eb1b0_0  
typing_extensions         4.1.1              pyh06a4308_0  
urllib3                   1.26.9           py38h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py38_1  
werkzeug                  2.0.3              pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py38h06a4308_0  
xz                        5.2.5                h7f8727e_1  
yapf                      0.31.0             pyhd3eb1b0_0  
yarl                      1.6.3            py38h27cfd23_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.8.0            py38h06a4308_0  
zlib                      1.2.12               h7f8727e_2  
zstd                      1.4.9                haebb681_0  

```
</details>

Could you give me some information on how to proceed?

Thanks!
Best regards!

**Comment by FullMetalNicky** [comment]
I'm running into the same problem.
@JosseVanDelm Did you manage to solve this?
